# Ejercicio 1 — Exploración de datos: Tennis Abstract Match Charting Project

**Jugador objetivo:** Novak Djokovic  
**Fuente:** JeffSackmann/tennis_MatchChartingProject (CC BY-NC-SA 4.0)  
**Objetivo de este notebook:** Carga inicial de los 10 CSV, visualización de primeras filas, tipos de datos y métricas básicas de calidad.

In [1]:
import pandas as pd
import os

# ─── Ajusta esta ruta si es necesario ───────────────────────────────────────
DATA_DIR = "../data"
# ─────────────────────────────────────────────────────────────────────────────

CSV_FILES = {
    "matches":          "charting-m-matches.csv",
    "overview":         "charting-m-stats-Overview.csv",
    "serve_basics":     "charting-m-stats-ServeBasics.csv",
    "serve_direction":  "charting-m-stats-ServeDirection.csv",
    "return_depth":     "charting-m-stats-ReturnDepth.csv",
    "return_outcomes":  "charting-m-stats-ReturnOutcomes.csv",
    "rally":            "charting-m-stats-Rally.csv",
    "net_points":       "charting-m-stats-NetPoints.csv",
    "kp_serve":         "charting-m-stats-KeyPointsServe.csv",
    "kp_return":        "charting-m-stats-KeyPointsReturn.csv",
}

print(f"Directorio de datos: {os.path.abspath(DATA_DIR)}")
print(f"Archivos esperados: {len(CSV_FILES)}")

Directorio de datos: c:\Users\pater\Desktop\DJOKOVIC\data
Archivos esperados: 10

In [2]:
# Carga de todos los CSV con manejo de errores de encoding
dfs = {}

for key, filename in CSV_FILES.items():
    filepath = os.path.join(DATA_DIR, filename)
    try:
        df = pd.read_csv(filepath, encoding="utf-8", low_memory=False)
    except UnicodeDecodeError:
        df = pd.read_csv(filepath, encoding="latin-1", low_memory=False)
    dfs[key] = df
    print(f"✓ {filename:<50} → {df.shape[0]:>6} filas × {df.shape[1]:>3} columnas")

✓ charting-m-matches.csv                             →   7566 filas ×  15 columnas
✓ charting-m-stats-Overview.csv                      →  56850 filas ×  20 columnas
✓ charting-m-stats-ServeBasics.csv                   →  45341 filas ×  12 columnas
✓ charting-m-stats-ServeDirection.csv                →  45341 filas ×  15 columnas
✓ charting-m-stats-ReturnDepth.csv                   → 270002 filas ×  12 columnas
✓ charting-m-stats-ReturnOutcomes.csv                → 310496 filas ×  11 columnas
✓ charting-m-stats-Rally.csv                         →  96706 filas ×  13 columnas
✓ charting-m-stats-NetPoints.csv                     →  59396 filas ×  11 columnas
✓ charting-m-stats-KeyPointsServe.csv                →  60464 filas ×  12 columnas
✓ charting-m-stats-KeyPointsReturn.csv               →  60464 filas ×   8 columnas

---
## 1. charting-m-matches.csv
Tabla principal de partidos. Contiene metadatos: fecha, torneo, superficie, rival, resultado.

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 40)
dfs["matches"].head(10)

,match_id,Player 1,Player 2,Pl 1 hand,Pl 2 hand,Date,Tournament,Round,Time,Court,Surface,Umpire,Best of,Final TB?,Charted by
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,R,R,20260521,Roland Garros,Q3,NaN,7,Clay,NaN,3,A,stard54
1,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,Jannik Sinner,R,R,20260517,Rome Masters,F,5pm,Centre,Clay,Renaud Lichtenstein,3,1,Edo
2,20260511-M-Rome_Masters-R16-Rafael_J...,Rafael Jodar,Learner Tien,R,L,20260511,Rome Masters,R16,NaN,NaN,Clay,NaN,3,1,stard54
3,20260507-M-Rome_Masters-R128-Stefano...,Stefanos Tsitsipas,Tomas Machac,R,R,20260507,Rome Masters,R128,4:35 PM,Paribas,Clay,R. Lichtenstein,3,1,BG
4,20260503-M-Madrid_Masters-F-Jannik_S...,Jannik Sinner,Alexander Zverev,R,R,20260503,Madrid Masters,F,NaN,NaN,Clay,NaN,3,1,Ludo
5,20260501-M-Madrid_Masters-SF-Arthur_...,Arthur Fils,Jannik Sinner,R,R,20260501,Madrid Masters,SF,NaN,NaN,Clay,NaN,3,1,Ludo
6,20260430-M-Madrid_Masters-QF-Alexand...,Alexander Zverev,Flavio Cobolli,R,R,20260430,Madrid Masters,QF,9pm,Santana,Clay,Adel Nour,3,1,Edo
7,20260429-M-Madrid_Masters-QF-Rafael_...,Rafael Jodar,Jannik Sinner,R,R,20260429,Madrid Masters,QF,NaN,Santana,Clay,NaN,3,1,Ludo
8,20260429-M-Madrid_Masters-QF-Arthur_...,Arthur Fils,Jiri Lehecka,R,R,20260429,Madrid Masters,QF,NaN,NaN,Clay,NaN,3,1,Ludo
9,20260428-M-Madrid_Masters-R16-Casper...,Casper Ruud,Stefanos Tsitsipas,R,R,20260428,Madrid Masters,R16,14:30,Arantxa Sanchez,Clay,Mohamed Lahyani,3,1,Julie DL

In [4]:
dfs["matches"].dtypes

match_id      object
Player 1      object
Player 2      object
Pl 1 hand     object
Pl 2 hand     object
Date          object
Tournament    object
Round         object
Time          object
Court         object
Surface       object
Umpire        object
Best of       object
Final TB?     object
Charted by    object
dtype: object

---
## 2. charting-m-stats-Overview.csv
Estadísticas globales por partido: puntos totales, errores no forzados, winners, etc.

In [5]:
dfs["overview"].head(10)

,match_id,player,set,serve_pts,aces,dfs,first_in,first_won,second_in,second_won,bk_pts,bp_saved,return_pts,return_pts_won,winners,winners_fh,winners_bh,unforced,unforced_fh,unforced_bh
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Total,80,6,4,48,33,32,13,11,8,61,18,25,13,5,25,15,6
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Total,61,3,2,34,27,27,16,3,3,80,34,28,23,2,21,11,8
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,1,52,6,2,32,22,20,8,7,6,34,9,18,8,3,13,7,4
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,1,34,2,1,19,14,15,11,0,0,52,22,18,15,1,12,8,3
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,2,28,0,2,16,11,12,5,4,2,27,9,7,5,2,12,8,2
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,2,27,1,1,15,13,12,5,3,3,28,12,10,8,1,9,3,5
6,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,1,25,0,0,13,12,12,5,1,0,31,14,10,5,5,11,5,6
7,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,Total,64,3,2,37,24,27,13,5,2,55,16,22,13,6,22,11,9
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,Total,55,2,0,35,29,20,10,2,1,64,27,27,15,10,18,9,9
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,1,31,2,1,19,12,12,5,3,1,25,8,10,5,3,13,8,4

In [6]:
dfs["overview"].dtypes

match_id          object
player            object
set               object
serve_pts          int64
aces               int64
dfs                int64
first_in           int64
first_won          int64
second_in          int64
second_won         int64
bk_pts             int64
bp_saved           int64
return_pts         int64
return_pts_won     int64
winners            int64
winners_fh         int64
winners_bh         int64
unforced           int64
unforced_fh        int64
unforced_bh        int64
dtype: object

---
## 3. charting-m-stats-ServeBasics.csv
Rendimiento al saque: % primer saque dentro, puntos ganados con 1S y 2S, dobles faltas.

In [7]:
dfs["serve_basics"].head(10)

,match_id,player,row,pts,pts_won,aces,unret,forced_err,pts_won_lte_3_shots,wide,body,t
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Total,80,46,6,1,9,22,27,5,48
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,1,48,33,6,1,7,17,18,1,29
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,2,32,13,0,0,2,5,9,4,19
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Total,61,43,3,0,4,17,22,3,36
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,1,34,27,3,0,4,13,12,1,21
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,2,27,16,0,0,0,4,10,2,15
6,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,Total,64,37,3,0,5,16,34,8,22
7,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,1,37,24,3,0,4,12,18,5,14
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,2,27,13,0,0,1,4,16,3,8
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,Total,55,39,2,0,9,20,31,7,17

In [8]:
dfs["serve_basics"].dtypes

match_id               object
player                 object
row                    object
pts                     int64
pts_won                 int64
aces                    int64
unret                   int64
forced_err              int64
pts_won_lte_3_shots     int64
wide                    int64
body                    int64
t                       int64
dtype: object

---
## 4. charting-m-stats-ServeDirection.csv
Dirección del saque: wide, body, T — por lado de la pista (deuce / advantage).

In [9]:
dfs["serve_direction"].head(10)

,match_id,player,row,deuce_wide,deuce_middle,deuce_t,ad_wide,ad_middle,ad_t,err_net,err_wide,err_deep,err_wide_deep,err_foot,err_unknown
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Total,8,1,33,19,4,15,16,6,11,3,0,0
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,1,6,1,18,12,0,11,0,0,0,0,0,0
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,2,2,0,15,7,4,4,16,6,11,3,0,0
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Total,3,1,28,19,2,8,9,4,14,2,0,0
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,1,3,0,15,9,1,6,0,0,0,0,0,0
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,2,0,1,13,10,1,2,9,4,14,2,0,0
6,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,Total,12,5,16,22,3,6,14,5,9,1,0,0
7,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,1,8,3,9,10,2,5,0,0,0,0,0,0
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,2,4,2,7,12,1,1,14,5,9,1,0,0
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,Total,12,6,12,19,1,5,7,3,8,2,0,0

In [10]:
dfs["serve_direction"].dtypes

match_id         object
player           object
row              object
deuce_wide        int64
deuce_middle      int64
deuce_t           int64
ad_wide           int64
ad_middle         int64
ad_t              int64
err_net           int64
err_wide          int64
err_deep          int64
err_wide_deep     int64
err_foot          int64
err_unknown       int64
dtype: object

---
## 5. charting-m-stats-ReturnDepth.csv
Profundidad del resto: shallow, medium, deep — indicador de agresividad al devolver.

In [11]:
dfs["return_depth"].head(10)

,match_id,player,row,returnable,shallow,deep,very_deep,unforced,err_net,err_deep,err_wide,err_wide_deep
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Total,52,13,37,10,4,0,1,3,0
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,v1st,27,8,20,5,0,0,0,0,0
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,v2nd,25,5,17,5,4,0,1,3,0
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,fh,16,4,10,2,3,0,1,2,0
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,bh,36,9,27,8,1,0,0,1,0
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,gs,50,12,36,10,4,0,1,3,0
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,sl,2,1,1,0,0,0,0,0,0
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,D,28,7,21,4,0,0,0,0,0
8,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,A,24,6,16,6,4,0,1,3,0
9,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,4,18,3,14,6,3,0,1,2,0

In [12]:
dfs["return_depth"].dtypes

match_id         object
player           object
row              object
returnable        int64
shallow           int64
deep              int64
very_deep         int64
unforced          int64
err_net           int64
err_deep          int64
err_wide          int64
err_wide_deep     int64
dtype: object

---
## 6. charting-m-stats-ReturnOutcomes.csv
Resultado del resto: en juego, error, winner — permite evaluar consistencia vs agresividad.

In [13]:
dfs["return_outcomes"].head(10)

,match_id,player,row,pts,pts_won,returnable,returnable_won,in_play,in_play_won,winners,total_shots
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Total,61,18,52,16,48,16,0,325
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,v1st,34,7,27,7,27,7,0,177
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,v2nd,25,9,25,9,21,9,0,146
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,7,13,2,12,2,12,2,0,87
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,89,37,14,37,14,36,14,0,227
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,9,10,6,10,6,10,6,0,48
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,fh,18,3,16,3,13,3,0,103
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,bh,38,13,36,13,35,13,0,217
8,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,gs,54,16,50,16,46,16,0,314
9,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,sl,2,0,2,0,2,0,0,6

In [14]:
dfs["return_outcomes"].dtypes

match_id          object
player            object
row               object
pts                int64
pts_won            int64
returnable         int64
returnable_won     int64
in_play            int64
in_play_won        int64
winners            int64
total_shots        int64
dtype: object

---
## 7. charting-m-stats-Rally.csv
Duración del rally por buckets (1-3, 4-6, 7-9, 10+) y puntos ganados en cada tramo.

In [15]:
dfs["rally"].head(10)

,match_id,server,returner,row,pts,pl1_won,pl1_winners,pl1_forced,pl1_unforced,pl2_won,pl2_winners,pl2_forced,pl2_unforced
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,Total,141,64,24,19,21,77,28,24,19
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,1-3,72,37,10,16,11,35,10,10,9
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,4-6,30,17,9,2,2,13,3,8,6
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,7-9,25,7,4,1,4,18,8,6,2
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,10,14,3,1,0,4,11,7,0,2
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,1-3-1,46,31,10,15,6,15,1,4,6
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,4-6-1,14,8,6,0,1,6,0,5,2
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,7-9-1,11,5,3,1,1,6,3,2,1
8,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Michael Zheng,10-1,9,2,0,0,3,7,4,0,2
9,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Jesper De Jong,1-3-2,26,20,9,6,3,6,0,1,5

In [16]:
dfs["rally"].dtypes

match_id        object
server          object
returner        object
row             object
pts              int64
pl1_won          int64
pl1_winners      int64
pl1_forced       int64
pl1_unforced     int64
pl2_won          int64
pl2_winners      int64
pl2_forced       int64
pl2_unforced     int64
dtype: object

---
## 8. charting-m-stats-NetPoints.csv
Puntos jugados y ganados en la red — frecuencia de subidas y efectividad.

In [17]:
dfs["net_points"].head(10)

,match_id,player,row,net_pts,pts_won,net_winner,induced_forced,net_unforced,passed_at_net,passing_shot_induced_forced,total_shots
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,NetPoints,16,13,8,4,1,1,0,80
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Approach,13,11,6,4,0,1,0,62
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,NetPointsRallies,13,11,6,4,1,1,0,70
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,ApproachRallies,10,9,4,4,0,1,0,52
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,NetPoints,11,9,6,2,1,1,0,99
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Approach,5,4,2,2,1,0,0,30
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,NetPointsRallies,11,9,6,2,1,1,0,99
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,ApproachRallies,5,4,2,2,1,0,0,30
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,NetPoints,11,7,4,3,0,4,0,56
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,Approach,10,7,4,3,0,3,0,50

In [18]:
dfs["net_points"].dtypes

match_id                       object
player                         object
row                            object
net_pts                         int64
pts_won                         int64
net_winner                      int64
induced_forced                  int64
net_unforced                    int64
passed_at_net                   int64
passing_shot_induced_forced     int64
total_shots                     int64
dtype: object

---
## 9. charting-m-stats-KeyPointsServe.csv
Rendimiento al saque en puntos clave: break points salvados, deuce, tie-break.

In [19]:
dfs["kp_serve"].head(10)

,match_id,player,row,pts,pts_won,first_in,aces,svc_winners,rally_winners,rally_forced,unforced,dfs
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,BP,11,8,6,1,1,2,2,1,1
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,BP,3,3,2,0,1,0,1,0,0
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,GP,13,8,10,1,1,2,1,2,1
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,GP,14,10,10,0,1,6,2,2,0
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,Deuce,13,8,6,2,2,2,0,2,0
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,Deuce,7,7,2,1,1,1,3,0,0
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,STotal,37,24,22,4,4,6,3,5,2
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,STotal,24,20,14,1,3,7,6,2,0
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,BP,5,2,2,0,1,1,0,1,0
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,BP,2,1,1,0,0,1,0,1,0

In [20]:
dfs["kp_serve"].dtypes

match_id         object
player           object
row              object
pts               int64
pts_won           int64
first_in          int64
aces              int64
svc_winners       int64
rally_winners     int64
rally_forced      int64
unforced          int64
dfs               int64
dtype: object

---
## 10. charting-m-stats-KeyPointsReturn.csv
Rendimiento al resto en puntos clave: break points convertidos, deuce, tie-break.

In [21]:
dfs["kp_return"].head(10)

,match_id,player,row,pts,pts_won,rally_winners,rally_forced,unforced
0,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,BPO,3,0,0,0,1
1,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,BPO,11,3,0,1,2
2,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,GPF,14,4,1,1,1
3,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,GPF,13,5,0,2,3
4,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,DeuceR,7,0,0,0,1
5,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,DeuceR,13,5,2,1,2
6,20260521-M-Roland_Garros-Q3-Jesper_D...,Jesper De Jong,RTotal,24,4,1,1,3
7,20260521-M-Roland_Garros-Q3-Jesper_D...,Michael Zheng,RTotal,37,13,2,4,7
8,20260517-M-Rome_Masters-F-Casper_Ruu...,Casper Ruud,BPO,2,1,0,0,0
9,20260517-M-Rome_Masters-F-Casper_Ruu...,Jannik Sinner,BPO,5,3,2,0,0

In [22]:
dfs["kp_return"].dtypes

match_id         object
player           object
row              object
pts               int64
pts_won           int64
rally_winners     int64
rally_forced      int64
unforced          int64
dtype: object

---
## Resumen de calidad — todas las tablas

In [23]:
resumen = []

for key, df in dfs.items():
    nulos_total = df.isnull().sum().sum()
    nulos_pct   = round(nulos_total / (df.shape[0] * df.shape[1]) * 100, 2)
    duplicados  = df.duplicated().sum()
    resumen.append({
        "Tabla":        key,
        "Filas":        df.shape[0],
        "Columnas":     df.shape[1],
        "Nulos totales": nulos_total,
        "% Nulos":      nulos_pct,
        "Duplicados":   duplicados,
    })

pd.DataFrame(resumen).set_index("Tabla")

                  Filas  Columnas  Nulos totales  % Nulos  Duplicados
Tabla
matches            7566        15           8577     7.56           0
overview          56850        20              0     0.00          56
serve_basics      45341        12              0     0.00          47
serve_direction   45341        15              0     0.00          47
return_depth     270002        12              0     0.00         323
return_outcomes  310496        11              0     0.00         378
rally             96706        13              0     0.00         107
net_points        59396        11              0     0.00          74
kp_serve          60464        12              0     0.00          84
kp_return         60464         8              0     0.00          84

---
## Columnas de cada tabla (referencia rápida)

In [24]:
for key, df in dfs.items():
    print(f"\n{'─'*60}")
    print(f"  {key.upper()}")
    print(f"{'─'*60}")
    for col in df.columns:
        print(f"  {col}")

────────────────────────────────────────────────────────────
  MATCHES
────────────────────────────────────────────────────────────
  match_id
  Player 1
  Player 2
  Pl 1 hand
  Pl 2 hand
  Date
  Tournament
  Round
  Time
  Court
  Surface
  Umpire
  Best of
  Final TB?
  Charted by

────────────────────────────────────────────────────────────
  OVERVIEW
────────────────────────────────────────────────────────────
  match_id
  player
  set
  serve_pts
  aces
  dfs
  first_in
  first_won
  second_in
  second_won
  bk_pts
  bp_saved
  return_pts
  return_pts_won
  winners
  winners_fh
  winners_bh
  unforced
  unforced_fh
  unforced_bh

────────────────────────────────────────────────────────────
  SERVE_BASICS
────────────────────────────────────────────────────────────
  match_id
  player
  row
  pts
  pts_won
  aces
  unret
  forced_err
  pts_won_lte_3_shots
  wide
  body
  t

────────────────────────────────────────────────────────────
  SERVE_DIRECTION
────────────────────────────────────────────────────────────
  match_id
  player
  row
  deuce_wide
  deuce_middle
  deuce_t
  ad_wide
  ad_middle
  ad_t
  err_net
  err_wide
  err_deep
  err_wide_deep
  err_foot
  err_unknown

────────────────────────────────────────────────────────────
  RETURN_DEPTH
────────────────────────────────────────────────────────────
  match_id
  player
  row
  returnable
  shallow
  deep
  very_deep
  unforced
  err_net
  err_deep
  err_wide
  err_wide_deep

────────────────────────────────────────────────────────────
  RETURN_OUTCOMES
────────────────────────────────────────────────────────────
  match_id
  player
  row
  pts
  pts_won
  returnable
  returnable_won
  in_play
  in_play_won
  winners
  total_shots

────────────────────────────────────────────────────────────
  RALLY
────────────────────────────────────────────────────────────
  match_id
  server
  returner
  row
  pts
  pl1_won
  pl1_winners
  pl1_forced
  pl1_unforced
  pl2_won
  pl2_winners
  pl2_forced
  pl2_unforced

────────────────────────────────────────────────────────────
  NET_POINTS
────────────────────────────────────────────────────────────
  match_id
  player
  row
  net_pts
  pts_won
  net_winner
  induced_forced
  net_unforced
  passed_at_net
  passing_shot_induced_forced
  total_shots

────────────────────────────────────────────────────────────
  KP_SERVE
────────────────────────────────────────────────────────────
  match_id
  player
  row
  pts
  pts_won
  first_in
  aces
  svc_winners
  rally_winners
  rally_forced
  unforced
  dfs

────────────────────────────────────────────────────────────
  KP_RETURN
────────────────────────────────────────────────────────────
  match_id
  player
  row
  pts
  pts_won
  rally_winners
  rally_forced
  unforced